services:
  - type: web
    name: youyan
    env: node
    plan: free
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: node server.mjs
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        generateValue: true